# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FjhGnECknDSKIowOk5PRIsjF7l4sU_4s
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/pba nyoba')  # Ganti dengan path folder Anda

!pip install keras # install keras library
!pip install tensorflow # install tensorflow library
import pandas as pd
import numpy as np
import re
import nltk
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer # use tensorflow.keras
from tensorflow.keras.preprocessing.sequence import pad_sequences # use tensorflow.keras
from tensorflow.keras.models import Sequential # use tensorflow.keras
from tensorflow.keras.layers import LSTM, GRU, Dense, Embedding, Dropout, SpatialDropout1D # use tensorflow.keras
from sklearn.metrics import accuracy_score
from gensim.models import FastText
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification

!python run_model.py